#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
# Copy pre-build lib
COPY ["./data/nuget", "./UploadFileService.API/nuget"]

COPY ["./solutions/UploadFileSolution/src/UploadFileService.API/UploadFileService.API.csproj", "./UploadFileService.API/"]
COPY ["./solutions/UploadFileSolution/src/UploadFileService.Application/UploadFileService.Application.csproj", "./UploadFileService.Application/"]
COPY ["./solutions/UploadFileSolution/src/UploadFileService.Domain/UploadFileService.Domain.csproj", "./UploadFileService.Domain/"]
COPY ["./solutions/UploadFileSolution/src/UploadFileService.Infrastructure/UploadFileService.Infrastructure.csproj", "./UploadFileService.Infrastructure/"]
COPY ["./solutions/Contract/Contract/bin/Release/net8.0/Contract.dll", "Contract/"]

WORKDIR /src/UploadFileService.API
RUN dotnet restore "./UploadFileService.API.csproj" --packages "./nuget" --verbosity normal
COPY ["./solutions/UploadFileSolution/src/", "/src/"]

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]