#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

USER app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./solutions/ChatHubSolution/src/ChatHub/ChatHub.csproj", "./ChatHub/ChatHub.csproj"]
COPY ["./solutions/Contract/Contract/bin/Release/net8.0/Contract.dll", "Contract/"]

WORKDIR /src/ChatHub
# Copy pre-build lib
COPY ["./data/nuget/websocket", "./nuget"]
RUN dotnet restore "./ChatHub.csproj" --packages "./nuget" --verbosity normal
COPY ["./solutions/ChatHubSolution/src/ChatHub/", "."]

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]