#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["ChatAPI/ChatAPI.csproj", "ChatAPI/"]
COPY ["BusinessObject/BussinessObject.csproj", "BusinessObject/"]
COPY ["DataAccess/DataAccess.csproj", "DataAccess/"]
RUN dotnet restore "./ChatAPI/./ChatAPI.csproj"
COPY . .
WORKDIR "/src/ChatAPI"
RUN dotnet build --no-restore "./ChatAPI.csproj" -o /app/build

FROM base AS final
WORKDIR /app
COPY --from=build /app/build .
COPY ./ChatAPI/certificate.pem .
COPY ./ChatAPI/key.pem .
ENTRYPOINT ["dotnet", "ChatAPI.dll"]