label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
      stroke: black
      font-color: black
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

Customer: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: <<user interaction>> \n chat application
apiGateway: <<coordinator>> \n apiGateway
identityService: <<service>> \n identityService
resourceService: <<service>> \n resourceService

DB: DB

Customer -> application.get: 1. User request resource
application.get -> apiGateway.get: 2. User request resource
apiGateway.get -> identityService.get: 3. User is unauthorized

apiGateWay.get <- identityService.get: 4. return login page {class: return arrow}
application.get <- apiGateway.get: 5. return login page {class: return arrow}
Customer <- application.get: 6. return login page {class: return arrow}
# Login
Customer -> application.post.login: 7. login(username, password)
application.post.login -> apiGateway.login: 8. login(username, password)
apiGateway.login -> identityService.post.login: 9. login(username, password)
identityService.post.login -> DB.login: 10. request database
identityService.post.login <- DB.login: 11. database response


alt: "alt" {
  class: frame

  if account not exist: "[if account not exist]" {
    class: frame

    apiGateway.login <- identityService.post.login: 12A. login failed {class: return arrow}
    application.post.login <- apiGateway.login: 12A.1. login failed {class: return arrow}
    Customer <- application.post.login: 12A.2. notify login failed
  }
  if account exist: "[if account exist]" {
    class: frame

    apiGateway.login <- identityService.post.login: 12. return authorization code {class: return arrow}
  }
}
application.post.login <- apiGateway.login: 13. return authorization code {class: return arrow}

# Request token
application.post.requestToken -> apiGateway.requestToken: 14. request token
apiGateway.requestToken -> identityService.post.requestToken: 15. request token
apiGateway.requestToken <- identityService.post.requestToken: 16. return access_token {class: return arrow}
application.post.requestToken <- apiGateway.requestToken: 17. return access_token {class: return arrow}

# Request resource
application.post.requestResource -> apiGateway.requestResource: 18. resource request
apiGateway.requestResource -> resourceService.get: 19. resource request
# Validate token
identityService.validateToken <- resourceService.get: 20. validate token
identityService.validateToken -> resourceService.get: 21. validate success {class: return arrow}
# Continue request resource
resourceService.get -> DB.get: 22. request database
resourceService.get <- DB.get: 23. response {class: return arrow}
apiGateway.requestResource <- resourceService.get: 24. resource response {class: return arrow}
application.post.requestResource <- apiGateway.requestResource: 25. resource request {class: return resource}
Customer <- application.post.requestResource: 26. resource response {class: return arrow}
