label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
      stroke: black
      font-color: black
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

Customer: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: <<user interaction>> \n application
apiGateway: <<coordinator>> \n apiGateway
identityService: <<service>> \n identityService
resourceService: <<service>> \n resourceService

DB: DB

Customer -> application.get: 1. User request resource
application.get -> apiGateway.get: 2. User request resource
apiGateway.get -> identityService.get: 3. User is unauthorized

apiGateWay.get <- identityService.get: 4. return login page {class: return arrow}
application.get <- apiGateway.get: 5. return login page {class: return arrow}
Customer <- application.get: 6. return login page {class: return arrow}
# Login
Customer -> application.post.login: 7. login(username, password)
application.post.login -> apiGateway.login: 8. login(username, password)
apiGateway.login -> identityService.post.login: 9. login(username, password)

alt: "alt" {
  class: frame

  if login failed: "[if login failed]" {
    class: frame

    apiGateway.login <- identityService.post.login: 10A. login failed {class: return arrow}
    application.post.login <- apiGateway.login: 10A.1. login failed {class: return arrow}
    Customer <- application.post.login: 10A.2. notify login failed
  }
  if login successfully: "[if login successfully]" {
    class: frame

    apiGateway.login <- identityService.post.login: 10. return code {class: return arrow}
  }
}
application.post.login <- apiGateway.login: 11. return code {class: return arrow}

# Request token
application.post.requestToken -> apiGateway.requestToken: 12. request token
apiGateway.requestToken -> identityService.post.requestToken: 13. request token
apiGateway.requestToken <- identityService.post.requestToken: 14. return access_token {class: return arrow}
application.post.requestToken <- apiGateway.requestToken: 15. request token {class: return arrow}

# Request resource
application.post.requestResource -> apiGateway.requestResource: 16. resource request
apiGateway.requestResource -> resourceService.get: 17. resource request
# Validate token
identityService.validateToken <- resourceService.get: 18. validate token
identityService.validateToken -> resourceService.get: 19. validate success {class: return arrow}
# Continue request resource
resourceService.get -> DB.get: 20. request database
resourceService.get <- DB.get: 21. response {class: return arrow}
apiGateway.requestResource <- resourceService.get: 22. resource response {class: return arrow}
application.post.requestResource <- apiGateway.requestResource: 23. resource request {class: return resource}
Customer <- application.post.requestResource: 24. resource response {class: return arrow}
