@startuml deleteTag
hide circle
skinparam classAttributeIconSize 0

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class TagsController {
    +Delete(DeleteTagDTO deleteTagDTO) Task<IActionResult>
}

class DeleteTagCommand {
    +TagId: Guid
}

class DeleteTagCommandHandler {
    -_context: IApplicationDbContext
    -_unitOfWork: IUnitOfWork
    +Handle(DeleteTagCommand request, CancellationToken cancellationToken): Task<Result>
}

class IApplicationDbContext {
    +Tags: DbSet<Tag>
}

class ApplicationDbContext {
    +Tags: DbSet<Tag>
    #OnConfiguring(DbContextOptionsBuilder optionsBuilder): void
}

class Result {
    +IsFailure: bool
    +IsSuccess: bool
    +Errors: IEnumerable<Error> 
    #Result(bool isSuccess, IEnumerable<Error> errors)
    #Result(bool isSuccess, Error error)
    +ThrowIfFailure(): void
    +{static} Success(): Result
    +{static} Failure(Error err): Result
    +{static} Failure(IEnumerable<Error> errs): Result
}

class Error {
    +{static} None: Error
    +{static} Result(Error err): implicit operator
}

class IUnitOfWork {
    SaveChangeAsync(CancellationToken cancellationToken = default): Task
}

class UnitOfWork {
    -_context: ApplicationDbContext
    +SaveChangeAsync(CancellationToken cancellationToken = default): Task
}

class TagError {
    +{static} NotFound: Error
    +{static} AlreadyExited: Error
}

class DeleteTagDTO {
    +Id: Guid
}

class BaseEntity {
    +Id: Guid 
}

class Tag {
    +Value: string
    +Code: string
}

interface "IRequest<TResponse>"
interface "IRequestHandler<TRequest, TResponse>"{
    Handle(TRequest request, CancellationToken cancellationToken): Task<TResponse>
}

'==== Delete Tag Post ====
'API Layer
TagsController --|> BaseApiController
TagsController -- DeleteTagCommand
TagsController -- DeleteTagDTO
'Application Layer
DeleteTagCommand ..|> "IRequest<TResponse>"
DeleteTagCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"
DeleteTagCommandHandler -- DeleteTagCommand
DeleteTagCommandHandler -- Result
DeleteTagCommandHandler -- IUnitOfWork
DeleteTagCommandHandler -- IApplicationDbContext
'Domain Layer
Result <|-- Error
Error -- TagError
Tag --|> BaseEntity
'Infrastructure Layer
IUnitOfWork <|.. UnitOfWork
IApplicationDbContext <|.. ApplicationDbContext
ApplicationDbContext --* Tag
@enduml