namespace ConversationService.Application.Conversations.Commands.CreateIndividualConversation;

public record CreateIndividualConversationCommand(ConversationWithMembersId ConversationWithMembersId) : IRequest;
