@startuml
hide circle
skinparam classAttributeIconSize 0
class FriendController {
    - _context: ApplicationDbContext
    - _httpContextAccessor: IHttpContextAccessor
    + Delete(DeleteFriendDTO deleteFriendDTO): Task<IActionResult>
}

class ApplicationDbContext {
    + Friends: DbSet<Friend>
    # OnConfiguring(DbContextOptionsBuilder optionsBuilder): void
}

class DeleteFriendDTO {
    + FriendId: string
}


class Friend{
    + UserId: string
    + FriendId: string
}


FriendController "1" o-- "1" ApplicationDbContext
FriendController "1" --"1" DeleteFriendDTO
ApplicationDbContext "1" o-- "1.*" Friend
@enduml