@startuml 
hide circle

class BaseApiController {
    #ISender _sender
    #HttpContextAccessor _httpContextAccessor
}

class PostsController {
    +async Task<IActionResult> CreateReportPost([FromBody]CreatePostReportDTO createPostReport)
}

class CreatePostReportCommand {
    +Guid PostId
    +Guid UserId
    +string Reason
}

class CreatePostReportCommandHandler {
    -readonly IApplicationDbContext _context
    -readonly IUnitOfWork _unitOfWork
    +async Task<Result> Handle(CreatePostReportCommand request, CancellationToken cancellationToken)
}

class IApplicationDbContext {
    +DbSet<Post> Posts
    +DbSet<PostReport> PostReports
}

class ApplicationDbContext {
    +DbSet<Post> Posts
    +DbSet<PostReport> PostReports
    #override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
}

class Result {
    +bool IsFailure
    +bool IsSuccess
    +IEnumerable<Error> Errors
    #Result(bool isSuccess, IEnumerable<Error> errors)
    #Result(bool isSuccess, Error error)
    +void ThrowIfFailure()
    +static Result Success()
    +static Result Failure(Error err)
    +static Result Failure(IEnumerable<Error> errs)
}

class Error {
    +static readonly Error None
    +static implicit operator Result(Error err)
}

class IUnitOfWork {
    Task SaveChangeAsync(CancellationToken cancellationToken = default)
}

class UnitOfWork {
    -readonly ApplicationDbContext _context
    +Task SaveChangeAsync(CancellationToken cancellationToken = default)
}

class PostError {
    +static Error NotFound
    +static Error UserNotFound
    +static Error AlreadyInteractedPost
    +static Error NotInteractedPost
}

class CreatePostReportDTO {
    +Guid PostId
    +string Reason
}

class BaseEntity {
    +Guid Id
}

class BaseAuditableEntity{
    +DateTime CreatedAt
    +DateTime UpdatedAt
}

class Post {
    +string Content
    +bool Active
    +Guid UserId
}

class PostReport {
    +Guid PostId
    +string Reason
    +Guid UserId
    +virtual Post Post
} 

PostsController --|> BaseApiController
PostsController --> CreatePostReportCommand
PostsController --> CreatePostReportDTO
CreatePostReportCommandHandler --> CreatePostReportCommand
CreatePostReportCommandHandler --> Result
CreatePostReportCommandHandler --> IUnitOfWork
CreatePostReportCommandHandler --> IApplicationDbContext
IUnitOfWork <|.. UnitOfWork
IApplicationDbContext <|.. ApplicationDbContext
Result <|-- Error
Error -- PostError
ApplicationDbContext --> PostReport
ApplicationDbContext --> Post
PostReport --|> BaseAuditableEntity
Post --|> BaseAuditableEntity
BaseAuditableEntity --|> BaseEntity
PostReport --* Post
@enduml