apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: general-secret
            - secretRef:
                name: api-gateway-secret
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Kubernetes"
          image: localhost:6000/chat-application-api-gateway
          name: apigateway
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
