apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: conversation-api
  name: conversation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conversation-api
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: conversation-api
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: general-secret
            - secretRef:
                name: conversation-api-secret
          image: localhost:6000/chat-application-conversation-api
          name: conversation-service
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
