apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: sql-server
  name: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sql-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: sql-server
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: general-secret
          image: mcr.microsoft.com/mssql/server:2022-latest
          livenessProbe:
            exec:
              command:
                - /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P PejOPjrzzBFkWnU0uJtevbZxEzyMfOWV -Q "SELECT 1" || exit 1
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          name: sqlserver
          ports:
            - containerPort: 1433
              protocol: TCP
      restartPolicy: Always
