apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: sql-server
  name: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sql-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: sql-server
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: general-secret
          image: mcr.microsoft.com/mssql/server:2022-latest
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                - /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "${SA_PASSWORD}" -Q "SELECT 1"
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          name: sqlserver
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
            - name: sql-server-storage
              mountPath: /var/opt/mssql/data
      restartPolicy: Always
      volumes:
        - name: sql-server-storage
          hostPath:
            path: /run/desktop/mnt/host/d/_Code/My_Project/Chat_Application/Chat-Application/data/db
            type: Directory
      securityContext:
        runAsUser: 0 #root
