label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
      stroke: black
      font-color: black
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: <<user interaction>> \n chat application
apiGateway: <<coordinator>> \n apiGateway
identityService: <<service>> \n identityService

DB: "DB" {
  shape: cylinder
}

User -> application.get: 1. User request with access token
application.get -> apiGateway.get: 2. User request with access token
apiGateway.get."3. validate token success"
apiGateway.get -> identityService.get: 4. Request update user

identityService.get -> identityService.get.getUser: 5. GetUserByOd
identityService.get.getUser -> Db.getUser: 6. Request database
identityService.get.getUser <- Db.getUser: 7. Database response {class: return arrow}

alt1: "alt" {
  class: frame

  if user not exist: "[if user not exist]" {
    class: frame

    apiGateway.get <- identityService.get: 8A. return 400 status {class: return arrow}
    application.get <- apiGateway.get: 8A.1. return 400 status {class: return arrow}
    User <- application.get: 8A.2. Display error {class: return arrow}
  }

  if user exist: "[if user exist]" {
    class: frame
    identityService.get.getUser -> identityService.get: 8. UpdateUser {class: return arrow}
  }
}

identityService.get -> DB.get: 9. Request database
identityService.get <- DB.get: 10. Database response {class: return arrow}

alt2: "alt" {
  class: frame
  if name not exist: "[if name not exist]" {
    class: frame
    apiGateway.get <- identityService.get: 11A. return 404 status {class: return arrow}
    application.get <- apiGateway.get: 11A.1 return 404 status {class: return arrow}
    User <- application.get: 11A.2 return 404 status {class: return arrow}
  }
  if name exist: "[if name exist]" {
    class: frame
    apiGateway.get <- identityService.get: 11. return User {class: return arrow}
    application.get <- apiGateway.get: 12. return User {class: return arrow}
    User <- application.get: 13. return User {class: return arrow}
  }
}
