#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
# Copy pre-build lib
COPY ["./data/nuget", "./NotificationService.API/nuget"]

COPY ["./solutions/NotificationSolution/src/NotificationService.API/NotificationService.API.csproj", "NotificationService.API/"]
COPY ["./solutions/NotificationSolution/src/NotificationService.Application/NotificationService.Application.csproj", "NotificationService.Application/"]
COPY ["./solutions/NotificationSolution/src/NotificationService.Infrastructure/NotificationService.Infrastructure.csproj", "NotificationService.Infrastructure/"]
COPY ["./solutions/NotificationSolution/src/NotificationService.Domain/NotificationService.Domain.csproj", "NotificationService.Domain/"]
COPY ["./solutions/Contract/Contract/bin/Release/net8.0/Contract.dll", "Contract/"]

# Building the services
WORKDIR "/src/NotificationService.API"
RUN dotnet restore --packages "./nuget" --verbosity normal
COPY ["./solutions/NotificationSolution/src","/src"]

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]
