label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
      stroke: black
      font-color: black
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

User2: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: <<user interaction>> \n chat application
signalRService: <<coordinator>> \n signalRService
serviceBus: <<coordinator>> \n serviceBus
conversationService: <<service>> \n conversationService

signalRService.call -> serviceBus.publishEndPoint: "Publish Call event"
serviceBus.publishEndPoint -> conversationService.consume: "Send client message to user"
conversationService.consume."Send client message to user"
