@startuml getPostByUserId
hide circle
skinparam classAttributeIconSize 0

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class PostsController {
    +GetByUserId(Guid userId): Task<IActionResult>
}

class GetPostsByUserIdQuery {
    +UserId: Guid
}

class GetPostsByUserIdQueryHandler {
    -_context: IApplicationDbContext
    +Handle(GetPostsByUserIdQuery request, CancellationToken cancellationToken): Task<Result<List<PostDTO>?>>
}

class IApplicationDbContext {
    +Posts: DbSer<Post>
    +Tags: DbSet<Tag>
    +PostTags: DbSet<PostTag> 
    +Interactions: DbSet<Interaction> 
    +PostInteracts: DbSet<PostInteract>
}

class ApplicationDbContext {
    +Posts: DbSer<Post>
    +Tags: DbSet<Tag>
    +PostTags: DbSet<PostTag> 
    +Interactions: DbSet<Interaction> 
    +PostInteracts: DbSet<PostInteract>
    #OnConfiguring(DbContextOptionsBuilder optionsBuilder): void
}

class Result {
    +IsFailure: bool
    +IsSuccess: bool
    +Errors: IEnumerable<Error>
    #Result(bool isSuccess, IEnumerable<Error> errors)
    #Result(bool isSuccess, Error error)
    +ThrowIfFailure(): void
    +{static} Success(): Result
    +{static} Failure(Error err): Result
    +{static} Failure(IEnumerable<Error> errs): Result
}

class "Result<T>" {
    +Value: T
    +{static} Success(T value): Result<T>
    +{static} Failure(Error error): Result<T?>
    +{static} Failure(IEnumerable<Error> errs): Result<T?>
}

class Error {
    +{static} None: Error 
    +{static} Result(Error err): implicit operator
}

class PostError {
    +{static} NotFound: Error
    +{static} UserNotFound: Error
    +{static} AlreadyInteractedPost: Error
    +{static} NotInteractedPost: Error
}

class PostDTO {
    +PostId: Guid
    +Content: string
    +UserId: Guid
    +InteractTotal: int
    +Interactions: List<string>
    +CreatedAt: DateTime 
    +Tags: List<string>
}

class BaseEntity {
    +Id: Guid
}

class BaseAuditableEntity{
    +CreatedAt: DateTime
    +UpdatedAt: DateTime
}

class Tag {
    +Value: string
    +Code: string
}

class Post {
    +Content: string
    +Active: bool
    +UserId: Guid
}

class PostTag {
    +PostId: Guid
    +TagId: Guid
    +Post: Post
    +Tag: Tag
}

class Interaction {
    +Value: string
    +Code: string
    +Gif: string
}

class PostInteract {
    +PostId: Guid
    +InteractionId: Guid
    +UserId: Guid
    +Post: Post
    +Interaction: Interaction
}

interface "IRequest<TResponse>"
interface "IRequestHandler<TRequest, TResponse>"{
    Handle(TRequest request, CancellationToken cancellationToken): Task<TResponse>
}

'==== Get Post By User Id====
'API Layer
PostsController --|> BaseApiController
PostsController --> GetPostsByUserIdQuery
'Application Layer
GetPostsByUserIdQuery ..|> "IRequest<TResponse>"
GetPostsByUserIdQueryHandler ..|> "IRequestHandler<TRequest, TResponse>"
GetPostsByUserIdQueryHandler --> GetPostsByUserIdQuery
GetPostsByUserIdQueryHandler --> Result
GetPostsByUserIdQueryHandler --> IApplicationDbContext
GetPostsByUserIdQueryHandler --> PostDTO
'Domain Layer
Result <|-- Error
Result <|-- "Result<T>"
Error -- PostError
Tag --|> BaseEntity
Interaction --|> BaseEntity
Post --|> BaseAuditableEntity
BaseAuditableEntity --|> BaseEntity
PostTag --* Post
PostTag --* Tag
PostInteract --* Post
PostInteract --* Interaction
'Infrastructure Layer
IApplicationDbContext <|.. ApplicationDbContext
ApplicationDbContext --> Tag
ApplicationDbContext --> Post
ApplicationDbContext --> PostTag
ApplicationDbContext --> Interaction
ApplicationDbContext --> PostInteract
@enduml