namespace ConversationService.Application.Conversations.Commands.CreateGroupConversation;

public record CreateGroupConversationCommand(GroupConversationWithMembersId ConversationWithMembersId) : IRequest;
