apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: post-api
  name: post-api
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 80
  selector:
    io.kompose.service: post-api
