apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kcompose\kompose.exe --file .\docker-compose-resolved.yaml convert -o kubernetes-configs
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: sql-server
  name: sql-server
spec:
  ports:
    - name: "2001"
      port: 2001
      targetPort: 1433
  selector:
    io.kompose.service: sql-server
