@startuml getFriendRequestListByUserId
hide circle
skinparam classAttributeIconSize 0

class FriendRequestController {
    - _context: ApplicationDbContext
    - _httpContextAccessor: IHttpContextAccessor
    + Get(): Task<IActionResult>
}

class ApplicationDbContext {
    + FriendRequests: DbSet<FriendRequest> 
    # OnConfiguring(DbContextOptionsBuilder optionsBuilder): void
}


class FriendRequest {
    + Id: Guid
    + SenderId: string 
    + ReceiverId: string 
    + Content: string 
    + Status: string 
    + CreatedAt: DateTime
    + Sender: ApplicationUser 
    + Receiver: ApplicationUser 
}

class FriendRequestResponseDTO{
    + Id: Guid
    + SenderId: string
    + Content: string
    + Status: string
    + CreatedAt: DateTime
}

FriendRequestController --> ApplicationDbContext
FriendRequestController --> FriendRequestResponseDTO
ApplicationDbContext --> FriendRequest
@enduml