label.style.font-color: black

classes: {
  text-black: {
    style: {
      font-color: black
    }
  }

  return arrow: {
    style: {
      stroke-dash: 3
      stroke: black
      font-color: black
    }
  }

  frame: {
    style: {
      fill: '#EAEDF0'
      stroke-width: 1
    }
  }

  label right: {
    style.font-color: black
  }
}

shape: sequence_diagram

User: {
  shape: image
  width: 50
  height: 60
  icon: https://upload.wikimedia.org/wikipedia/commons/5/5b/Robustness_Diagram_Actor.svg
}

application: <<user interaction>> \n chat application
apiGateway: <<coordinator>> \n apiGateway
identityService: <<service>> \n identityService

DB: DB

User -> application.get: 1. User request with access token
application.get -> apiGateway.get: 2. User request with access token
apiGateway.get."3. validate token success"
apiGateway.get -> identityService.get: 4. User request with access token
identityService.get -> DB.get: 5. Request database
identityService.get <- DB.get: 6. Database response {class: return arrow}
alt: "alt" {
  class: frame
  if id not exist: "[if id not exist]" {
    class: frame
    apiGateway.get <- identityService.get: 7A. return 404 status {class: return arrow}
    application.get <- apiGateway.get: 7A.1 return 404 status {class: return arrow}
    User <- application.get: 7A.2 return 404 status {class: return arrow}
  }
  if id exist: "[if id exist]" {
    class: frame
    apiGateway.get <- identityService.get: 7. return User {class: return arrow}
    application.get <- apiGateway.get: 8. return User {class: return arrow}
    User <- application.get: 9. return User {class: return arrow}
  }
}
